# Generated by Django 3.1.2 on 2020-10-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelis',
            fields=[
                ('cod_peli', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_peli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la pelicula')),
                ('imagen', models.TextField(blank=True, null=True)),
                ('fecha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de estreno')),
                ('plot', models.TextField(verbose_name='Sinopsis')),
                ('value', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMDB Rating ')),
                ('fav', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
